DROP DATABASE IF EXISTS AllStarBlogTest;

CREATE DATABASE IF NOT EXISTS AllStarBlogTest;

USE AllStarBlogTest;

CREATE TABLE IF NOT EXISTS HashTag (
HashTagID INT NOT NULL AUTO_INCREMENT,
Tag VARCHAR(150) NOT NULL,
PRIMARY KEY (HashTagID));

CREATE TABLE IF NOT EXISTS `Profile` (
ProfileID INT NOT NULL AUTO_INCREMENT,
UserName VARCHAR(150) NOT NULL,
`Password` VARCHAR(70) NOT NULL,
FirstName VARCHAR(75) NOT NULL,
LastName VARCHAR(75) NOT NULL,
Email VARCHAR(75) NOT NULL,
Birthday Date NULL,
AdminID BOOLEAN NOT NULL,
PRIMARY KEY (ProfileID));

CREATE TABLE IF NOT EXISTS Post (
PostID INT NOT NULL AUTO_INCREMENT,
Picture VARCHAR(100) NULL,
Title VARCHAR(100) NULL,
Description VARCHAR(5000) NOT NULL,
Pending BOOLEAN NOT NULL,
Blog BOOLEAN NOT NULL,
`Date` Date NOT NULL,
ProfileID INT NOT NULL,
PRIMARY KEY (PostID),
CONSTRAINT fk_Post_ProfileID
FOREIGN KEY (ProfileID)
REFERENCES `Profile`(ProfileID));

CREATE TABLE IF NOT EXISTS PostHashTag (
PostID INT NOT NULL,
HashTagID INT NOT NULL,
CONSTRAINT fk_PostHashTag_PostID
FOREIGN KEY (PostID)
REFERENCES Post(PostID),
CONSTRAINT fk_PostHashTag_HashTagID
FOREIGN KEY (HashTagID) 
REFERENCES HashTag(HashTagID));